- name: ansible_host variable Demo
  hosts: all*

  gather_facts: true

  tasks:

    - name: Print Facts
      ansible.builtin.copy:
        dest: /tmp/info.txt
        content: |
            Kernel        = {{ ansible_facts['kernel'] }}
            RAM Free      = {{ ansible_facts['memory_mb']['real']['free'] }}
            RAM Total     = {{ ansible_facts['memory_mb']['real']['total'] }}
            User Name     = {{ ansible_facts.ansible_local.emp.user.emp_name }}
            User Dept     = {{ ansible_facts['ansible_local']['emp']['dept']['dept_name'] }}
