- name: Dependency Task WIth Handlers
  hosts: servera.lab.example.com
  gather_facts: false
  become: true
  remote_user: devops
  # force_handlers: true
  tasks:
    - name: Install web package
      ansible.builtin.dnf:
        name: httpd
        state: present
      register: captured
      changed_when: captured.changed == false
      notify:
        - Restart and Enable Service
        - Package Installed

    - name: Print the Output
      ansible.builtin.debug:
        msg: "{{ captured }}"

    - name: Deploy an App
      ansible.builtin.copy:
        content: "Hello Class {{ inventory_hostname }}"
        dest: /var/www/html/index.html
        mode: 0644
      notify:
        - Restart and Enable Service
        - Service Restarted
        - App Deployed

    - name: Open firewall Port
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true


  handlers:
    - name: Package Installed
      ansible.builtin.debug:
        msg: "Package installed successfully"

    - name: App Deployed
      ansible.builtin.debug:
        msg: "My App Deployed"

    - name: Service Restarted
      ansible.builtin.debug:
        msg: "Service DONE"

    - name: Restart and Enable Service
      ansible.builtin.service:
        name: httpd
        state: restarted
        enabled: true
