- name: Check Mode Demo
  hosts: servera.lab.example.com
  gather_facts: false
  become: true
  remote_user: devops
  tasks:
    - name: Install web package
      ansible.builtin.dnf:
        name: httpd
        state: present
      check_mode: false

    - name: Deploy an App
      ansible.builtin.copy:
        content: "Hello Class {{ inventory_hostname }}"
        dest: /var/www/html/index.html
        mode: 0644
      check_mode: true

    - name: Open firewall Port
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      # check_mode: true

    - name: Start and Enable Service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      check_mode: true
