- name: Facts Demo
  hosts: servera*

  gather_facts: false
  vars_files:
    - vars/outside_vars.yml

  tasks:
    - name: Collect Facts Manually
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'min'
          - 'network'
          - 'hardware'

    - name: Print Facts
      ansible.builtin.copy:
        dest: /tmp/info.txt
        content: |
            Magic Inventory = {{ inventory_hostname }}
            Architecture  = {{ ansible_architecture }}
            Architecture  = {{ ansible_facts.architecture }}
            Architecture  = {{ ansible_facts['architecture'] }}
            Date          = {{ ansible_facts['date_time']['date'] }}
            Time          = {{ ansible_facts['date_time']['time'] }}
            IP Address    = {{ ansible_facts['default_ipv4']['address'] }}
            MAC Address   = {{ ansible_facts['default_ipv4']['macaddress'] }}
            VDA Size      = {{ ansible_facts['devices']['vda']['size'] }}
            OS            = {{ ansible_facts['distribution'] }}
            FQDN          = {{ ansible_facts['fqdn'] }}
            Hostname      = {{ ansible_facts['hostname'] }}
            Kernel        = {{ ansible_facts['kernel'] }}
            RAM Free      = {{ ansible_facts['memory_mb']['real']['free'] }}
            RAM Total     = {{ ansible_facts['memory_mb']['real']['total'] }}
            Python Ver    = {{ ansible_facts['python_version'] }}
            User Name     = {{ ansible_facts.ansible_local.emp.user.emp_name }}
            User Dept     = {{ ansible_facts['ansible_local']['emp']['dept']['dept_name'] }}

    - name: Install a package
      ansible.builtin.dnf:
        name: httpd
        state: present
      when:
        - ansible_facts['ansible_local']['emp']['dept']['dept_name'] == "security"
        - ansible_facts['memory_mb']['real']['free'] >= 400 or youyou is not defined
        -  user_name not in users_list
      vars:
        user_name: 'navdeep'

      # when: ansible_facts['ansible_local']['emp']['dept']['dept_name'] == "security" and  ansible_facts['memory_mb']['real']['free'] <= 400
      become: true
