- name: First Playbook
  hosts: servera.lab.example.com
    #remote_user: devops
  gather_facts: false
  tasks:
    - name: Create a File
      ansible.builtin.copy:
        content: "Hello Class RH294"
        dest: /tmp/abc
        #ansible.builtin.copy: content="Hello Class" dest=/tmp/abc
        #
    - name: Install a package
      ansible.builtin.dnf:
        name: httpd
        state: present
          #become: true
        #become_method: sudo
        #become_user: root
