- name: Ignore Errors Play
  hosts: servera.lab.example.com
  gather_facts: false
  become: true
  remote_user: devops
  # ignore_errors: true
  tasks:
    - name: Test Web Server A
      ansible.builtin.uri:
        url: http://servera.lab.example.com/index.html
        return_content: true
      ignore_errors: true

    - name: Install web package
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Deploy an App
      ansible.builtin.copy:
        content: "Hello Class {{ inventory_hostname }}"
        dest: /var/www/html/index.html
        mode: 0644

    - name: Open firewall Port
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Start and Enable Service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
