- name: First Playbook
  hosts: servera.lab.example.com
  gather_facts: false
  tasks:
    - name: Create a File
      ansible.builtin.copy:
        content: "Hello Class {{ inventory_hostname }}"
        dest: /tmp/abc

    - name: Install a package
      ansible.builtin.dnf:
        name: httpd
        state: present

- name: Second Playbook
  hosts: serverb.lab.example.com
  gather_facts: false
  tasks:
    - name: Create a File in serverb
      ansible.builtin.copy:
        content: "Hello Class RH294 on $HOSTNAME"
        dest: /tmp/ross_happy
