- name: Verbosity Demo
  hosts: servera.lab.example.com
  gather_facts: false
  become: true
  remote_user: devops
  tasks:
    - name: Install web package
      ansible.builtin.dnf:
        name: httpd
        state: present
      register: captured

    - name: Print the captured output
      ansible.builtin.debug:
        # msg: "{{ captured }}"
        var: captured
        verbosity: 2

    - name: Restart and Enable Service
      ansible.builtin.service:
        name: httpd
        state: restarted
        enabled: true
      when: captured.changed
