- name: Dependency Task WIth Handlers
  hosts: servera.lab.example.com
  gather_facts: false
  become: true
  remote_user: devops
  tasks:
    - name: Install web package
      ansible.builtin.dnf:
        name: httpd
        state: present
      notify:
        - Restart and Enable Service
        - Package Installed

    - name: RUN ALL HANDLERS RIGHT NOW
      ansible.builtin.meta: flush_handlers

    - name: Deploy an App
      ansible.builtin.copy:
        content: "Hello Class {{ inventory_hostname }}"
        dest: /var/www/html/index.html
        mode: 0644
      notify:
        - Restart and Enable Service
        - Service Restarted

  handlers:
    - name: Package Installed
      ansible.builtin.debug:
        msg: "Package installed successfully"

    - name: Extra
      ansible.builtin.debug:
        msg: "Very Extra"

    - name: Service Restarted
      ansible.builtin.debug:
        msg: "Service DONE"

    - name: Restart and Enable Service
      ansible.builtin.service:
        name: httpd
        state: restarted
        enabled: true
