---
# tasks file for web_server

- name: Install web package
  ansible.builtin.dnf:
    name: "{{ web_server_package }}"
    state: present
  notify:
    - Restart and Enable Service
    - Package Installed

- name: Deploy an App
  ansible.builtin.copy:
    content: "{{ web_server_content }}"
    dest: "{{ web_server_file }}"
    mode: 0644
  notify:
    - Restart and Enable Service
    - Service Restarted

